apiVersion: v1
kind: Pod
metadata:
  name: august-2022-app
spec:
  containers:
  - name: august-2022-app
    image: bmukum/august-2022-app:v15
    ports:
    - containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      - name: tomcat
        image: image
        ports:
        - containerPort: 81

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-pod
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3