name: build
on:
  push:
    branches:
    - master
    - main
    paths:
    - app/**
  pull_request:
    branches:
    - master
    - main
    paths:
    - app/**

env:
  image: august-2022-app
  username: bmukum

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: app

    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the docker images
      run: |
        docker build -t ${{ env.username }}/${{ env.image }}:v$GITHUB_RUN_NUMBER .
      
    - name: Login to dockerhub
      run: docker login -u ${{ env.username }} -p ${{ secrets.DOCKERHUB_PW }}
      
    - name: Push docker image to dockerhub
      if: github.ref == 'refs/heads/main'
      run: |
        docker push ${{ env.username }}/${{ env.image }}:v$GITHUB_RUN_NUMBER

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup kubectl
      if: github.ref == 'refs/heads/main'
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
        kubectl-version: v1.23.0
    - name: update the app
      if: github.ref == 'refs/heads/main'
      run: kubectl set image deployment/august-2022-app august-2022-app=bmukum/august-2022-app:v$GITHUB_RUN_NUMBER

