name: build
on:
  push:
    branches:
    - master
    - main
    paths:
    - app/**
  pull_request:
    branches:
    - master
    - main
    paths:
    - app/**

env:
  image: august-2022-app
  username: bmukum

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: app

    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the docker images
      run: |
        docker build -t ${{ env.username }}/${{ env.image }}:v$GITHUB_RUN_NUMBER .
      
    - name: Login to dockerhub
      run: docker login -u ${{ env.username }} -p ${{ secrets.DOCKERHUB_PW }}
      
    - name: Push docker image to dockerhub
      if: github.ref == 'refs/heads/main'
      run: |
        docker push ${{ env.username }}/${{ env.image }}:v$GITHUB_RUN_NUMBER

    - name: Setup kubectl
      if: github.ref == 'refs/heads/main'
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: set image deployment/${{ env.image }} ${{ env.image }}=${{ env.image }}:$GITHUB_RUN_NUMBER

